services:
  reactjs-ui:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    container_name: reactjs-ui
    volumes:
      - './src:/app/src'
    networks:
      - my-network

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/prod:/etc/nginx/conf.d
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    networks:
      - my-network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  my-network: